# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Envolve < Formula
  desc "Synchronize environment variables across projects and manage .env files. Automates the restoration of .env files for all projects, ensures consistency by syncing variables from a global .env file, and creates symbolic links to maintain the latest environment settings."
  homepage "https://erdemkosk.github.io/envolve-app/"
  version "1.0.1"

  on_macos do
    on_intel do
      url "https://github.com/erdemkosk/envolve/releases/download/v1.0.1/envolve_Darwin_x86_64.tar.gz", using: CurlDownloadStrategy
      sha256 "29e3286b7b5df352c626d2516207533e1a816fef75452cbf19d359eda40792a0"

      def install
        bin.install "envolve"
      end
    end
    on_arm do
      url "https://github.com/erdemkosk/envolve/releases/download/v1.0.1/envolve_Darwin_arm64.tar.gz", using: CurlDownloadStrategy
      sha256 "a8c07292b811c84e9e7f95adeb67d554062b2fb23e58df9ea3b3ed8d6b914da5"

      def install
        bin.install "envolve"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/erdemkosk/envolve/releases/download/v1.0.1/envolve_Linux_x86_64.tar.gz", using: CurlDownloadStrategy
        sha256 "d05adaacf6e013d60134b99669fd7921871150e1ad53edb4d51156afcbe9c42a"

        def install
          bin.install "envolve"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/erdemkosk/envolve/releases/download/v1.0.1/envolve_Linux_arm64.tar.gz", using: CurlDownloadStrategy
        sha256 "5af0706510cdfce9ae95046738abbab0f0ad05d77789b9da658654d8b85575fa"

        def install
          bin.install "envolve"
        end
      end
    end
  end
end
