# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Gophersay < Formula
  desc "Synchronize environment variables across projects and manage .env files. Automates the restoration of .env files for all projects, ensures consistency by syncing variables from a global .env file, and creates symbolic links to maintain the latest environment settings."
  homepage "https://github.com/erdemkosk/homebrew-envolve"
  version "1.0.0"

  on_macos do
    on_intel do
      url "https://github.com/erdemkosk/envolve/releases/download/v1.0.0/envolve_Darwin_x86_64.tar.gz", using: CurlDownloadStrategy
      sha256 "cf0a42b67272e2f823b14cc72c13508656d28bdba492bcbd2d0575a187fbb352"

      def install
        bin.install "gophersay"
      end
    end
    on_arm do
      url "https://github.com/erdemkosk/envolve/releases/download/v1.0.0/envolve_Darwin_arm64.tar.gz", using: CurlDownloadStrategy
      sha256 "0cca07c18ca275c3aa94e5893276311e07d174514bf7d115ecb16c200b86d1e6"

      def install
        bin.install "gophersay"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/erdemkosk/envolve/releases/download/v1.0.0/envolve_Linux_x86_64.tar.gz", using: CurlDownloadStrategy
        sha256 "29feaf1e40005e8aef98ef4ef12a92e514485b2a0cb8de4a6f61e1814195749c"

        def install
          bin.install "gophersay"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/erdemkosk/envolve/releases/download/v1.0.0/envolve_Linux_arm64.tar.gz", using: CurlDownloadStrategy
        sha256 "c07e391a2dd11aa32420d671eab8d72a53b608862e35001838499c30a4c2f31f"

        def install
          bin.install "gophersay"
        end
      end
    end
  end
end
