# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Envolve < Formula
  desc "Synchronize environment variables across projects and manage .env files. Automates the restoration of .env files for all projects, ensures consistency by syncing variables from a global .env file, and creates symbolic links to maintain the latest environment settings."
  homepage "https://erdemkosk.github.io/envolve-app/"
  version "1.0.2"

  on_macos do
    on_intel do
      url "https://github.com/erdemkosk/envolve/releases/download/v1.0.2/envolve_Darwin_x86_64.tar.gz", using: CurlDownloadStrategy
      sha256 "dfc4b24aed56991d813e424dd50c0f2da2f970eaf7eb3459c7b99e2eb1c8806e"

      def install
        bin.install "envolve"
      end
    end
    on_arm do
      url "https://github.com/erdemkosk/envolve/releases/download/v1.0.2/envolve_Darwin_arm64.tar.gz", using: CurlDownloadStrategy
      sha256 "48d32b229764c84d88cdcd3955e27cea6df3bd4b0f711be84d77901a63a3306d"

      def install
        bin.install "envolve"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/erdemkosk/envolve/releases/download/v1.0.2/envolve_Linux_x86_64.tar.gz", using: CurlDownloadStrategy
        sha256 "323cfbf50bd1807bd70e988131ecd5ad20d18384cfa865f513f1e6cdeecce58b"

        def install
          bin.install "envolve"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/erdemkosk/envolve/releases/download/v1.0.2/envolve_Linux_arm64.tar.gz", using: CurlDownloadStrategy
        sha256 "93593c4759ba8a780cdb2532d4e5c97504b2520a03ce47e6e5454746148b3723"

        def install
          bin.install "envolve"
        end
      end
    end
  end
end
